print("hello world!")
print("Hello Again")
print("I like typing this")
print("i m gonna do it")
print("im stciking to my goal")
print("Yay!printing.")
print("I'd much ratger you 'not'")
print("i 'said'do not touch thisss")
print("ima nooop no more")
print("i have it inside me")
